CREATE TABLE Cities
(
	CityID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Customers
(
	CustomerID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
	Birthday DATE,
	CityID INT NOT NULL

	CONSTRAINT FK_CityID FOREIGN KEY (CityID) REFERENCES Cities(CityID)
)

CREATE TABLE ItemTypes
(
	ItemTypeID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Items
(
	ItemID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
	ItemTypeID INT NOT NULL

	CONSTRAINT FK_Item_ItemType FOREIGN KEY (ItemTypeID) REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE Orders
(
	OrderID INT PRIMARY KEY IDENTITY,
	CustomerID INT NOT NULL
)

ALTER TABLE Orders
ADD CONSTRAINT FK_Orders_CustomerID FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)

CREATE TABLE OrderItems
(
	OrderID INT,
	ItemID INT

	CONSTRAINT FK_Order_Item PRIMARY KEY (OrderID, ItemID),
	CONSTRAINT PK_Order FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
	CONSTRAINT PK_Item FOREIGN KEY (ItemID) REFERENCES Items(ItemID)
)
